#import "../graceful-genetics/src/lib.typ" as graceful-genetics
#import "@preview/cetz:0.4.2" as cetz

// Fortris brand colors
#let gray = rgb("#2f3849")
#let red = rgb("#F07C70")
#let white = rgb("#F8F7F8")
#let lightgray = rgb("#C9CED8")

#show: graceful-genetics.template.with(
  title: [2025: The Year Engineering Stopped Guessing],
  authors: (
    (
      name: "Leveling-up the Platform",
      department: "Platform Engineering",
      institution: "",
      city: "Malaga",
      country: "Spain",
      mail: "",
    ),
  ),
  date: (
    year: 2026,
    month: "January",
    day: 01,
  ),
  keywords: (
    "Platform Engineering",
    "Kubernetes",
    "StatefulSets",
    "Infisical",
    "ArgoCD",
    "STS",
    "OpenTelemetry",
    "Tempo",
    "Argo Rollouts",
    "GitLab Runners",
    "Cost Attribution",
  ),
  doi: "10.0000/fortris.platform.2025.v2",
  abstract: [
    2025 turned platform decisions into defaults and made AI practical in daily
    delivery: agentic assistance and AI release intelligence reduced friction
    while keeping judgment in the loop. Kubernetes became the runtime, stateful
    systems gained first-class support, security moved toward runtime identity,
    and CI/CD became deterministic. Advanced delivery and tracing shipped as
    bounded experiments. Cost, ownership, and operational risk became measurable
    instead of assumed.
  ],
)

#set text(font: ("Manrope", "Arial", "Helvetica"), fill: gray)

#let bar-chart(values, caption, scale) = {
  let maxv = values.fold(0, (acc, v) => if v > acc { v } else { acc })
  let labels = (1, 2, 3, 4, 5)

  [
    #block(width: 70mm)[
      #align(center)[
        #text(
          size: 6.5pt,
          font: ("Helvetica Neue", "Helvetica"),
          weight: "regular",
          style: "italic",
          fill: gray
        )[#scale]
      ]
    ]
    #cetz.canvas(length: 1mm, {
      import cetz.draw: *
      let width = 70
      let height = 26
      let gap = 4
      let barw = 8
      let base = 5

      line((0, base), (width, base), stroke: 0.4pt + lightgray)
      line((0, base), (0, base + height), stroke: 0.4pt + lightgray)

      for i in range(0, 5) {
        let x = 6 + i * (barw + gap)
        let h = if maxv == 0 { 0 } else { values.at(i) / maxv * height }
        rect((x, base), (rel: (barw, h)), fill: lightgray, stroke: none)
        content((x + barw / 2, base - 2), [#labels.at(i)], anchor: "mid")
      }
    })
    #v(2pt)
    #block(width: 70mm)[
      #align(center)[
        #text(
          size: 7pt,
          font: ("Helvetica Neue", "Helvetica"),
          weight: "bold",
          tracking: -0.2pt
        )[#caption]
      ]
    ]
  ]
}

= AI, Bounded and Useful
Agentic AI coding assistance was adopted with top-tier models (i.e. Claude 4.5) exceling at coding tasks, delivered via Amazon Q
Developer#link("ref1", super[[1]]). The goal: increase engineering productivity and flow.

#bar-chart(
  (2, 10, 13, 9, 2),
  [Figure 1: Task complexity solved with AI],
  [Scale: 1 = very simple, 5 = very complex],
)
#v(2mm)

Survey results make the value clear: AI helps with medium-complex tasks, developer experience ratings sit near the top of the scale, and teams now delegate to AI  a significant amount of their daily tasks.

#bar-chart(
  (1, 3, 5, 15, 12),
  [Figure 2: AI assistant code contribution and delegation],
  [Scale: 1 = none, 5 = most of the task],
)
We adopted the latest industry AI patterns while keeping engineering judgment in the loop, and addressing AI-era security risks with a secure rollout for engineers.
#v(2mm)
#bar-chart(
  (2, 1, 2, 10, 21),
  [Figure 3: AI developer experience],
  [Scale: 1 = did not help, 5 = very helpful],
)

These figures come from an engineering-wide survey on AI usage and experience at Fortris.

AI entered the engineering teams without pretending to be magic.

Release notes were generated by AI from commits #link("ref2", super[[2]]), GitLab AI bots assisted merge requests #link("ref3", super[[3]]),
and failed Kubernetes syncs jobs triggered automated AI context analysis to help developers understand outside their comfort zone where the problem is #link("ref4", super[[4]]).



= Working With Humans
Reliability is leverage only if people can use it.

Preview environments #link("ref5", super[[5]]) matured into a collaboration tool for UI teams and QA teams.
Deployments became comprehensive: ci/cd job logs surfaced reasons, ArgoCD state became
visible inside pipelines, and rocketchat notifications began reducing guesswork.

Delivery started becoming less of a coordination tax.

= Direction, Not Hope
The year opened decisively: Kubernetes would be the system of record, not a parallel path.

MongoDB control moved into Kubernetes via platform-owned Helm charts #link("ref6", super[[6]]) #link("ref7", super[[7]]). Infisical became the central secret manager #link("ref8", super[[8]]), replacing scattered values files and pipeline variables. CI/CD learned how to deploy to real Kubernetes environments, including production.

Nothing here was flashy. It was alignment.

= State, Limits, and Operability
If a platform cannot handle state, it is a scheduler.

StatefulSets were added to the base application chart. MongoDB and Redis #link("ref9", super[[9]]) gained
supported Helm charts with operating guides. Resource quotas and limit ranges
became explicit defaults across namespaces. Vault backup tooling was rebuilt
with health checks, encryption signatures, and observability.

This did not make systems simpler. It made them survivable.

= Stability as a Precondition
Before production confidence, instability had to be removed.

Registry access was centralized through a platform-managed chart. Pod
Disruption budgets and rolling update strategies were aligned with availability
realities. Automatic reloads were disabled for stateful Vault and Sentinel
workloads. ArgoCD diffing was tuned to reduce false drift and explain failures.

The platform stopped surprising people. That is what trust starts with.

= Production Trust, Earned
Theory met consequence when BCoin, our main bridge with the Bitcoin blockchain, went live on Kubernetes using Helm and
GitOps-managed workflows. Legacy paths were not forcibly shut down. They simply became unnecessary.

Kubernetes moved from "some services run here" to "production belongs here."

= Irreversible Moves
Once the Kubernetes platform worked, it began to lock in the future.

Keycloak moved fully into Kubernetes. RDS integration became a supported capability for Kubernetes workloads. STS assume-role patterns replaced static AWS credentials for almost all platform tooling.

CI/CD pipelines stopped wasting time: merge request pipelines canceled outdated runs, ArgoCD sync jobs failed fast, and preview environments gained lifecycle rules instead of leaking namespaces.

This was not innovation. It was discipline.

= Scale Without Waste
As confidence grew, some waste became visible.

Artifact retention policies reduced GitLab and Nexus footprints. GitLab Runners were isolated and right-sized. Spot capacity was introduced carefully in dev. Cost attribution aimed at becoming explicit through Kubernetes metadata tied to teams and products.

The platform became lighter as it grew.

= Automation as a Delivery System
Automation stopped being a side project and became part of the delivery path.

Genaro David stepped up to lead QA execution, and Software Engineers in Test (SETs) moved into an enabler pod with domain ownership and a single Jira backlog. E2E suites and performance tests were stabilized through a dedicated SET firefight loop that detects and fixes instability early. Quality gates became more explicit, so release decisions started to rely on signal instead of guesswork.

The outcome was fewer ignored failures, clearer signals, and automation teams that can be trusted when delivery is moving fast.

// = Experiments That Stayed Honest
// Two capabilities remained pending to continue implementing in 2026.

// *Progressive Delivery (Argo Rollouts)*
// Canary deployments as opt-in and environment-limited. Aims for teams to progressively shift traffic and pause rollouts, but this is still work in progress.

// *Distributed Tracing (OpenTelemetry + Tempo)*
// Tracing pipelines are halfway available in development with Alloy and Tempo. Instrumentation coverage remains to be explored in 2026.

= What 2025 Actually Delivered
2025 did not deliver perfection. It delivered control and enabled reliability foundations.

Kubernetes is now the default runtime. Stateful workloads are supported, not improvised. Security relies less on static secrets and more on runtime identity. Delivery pipelines are deterministic and explain themselves. AI reduces toil without increasing risk.

Most importantly, decisions stopped being less of guesses and start being informed. Risk is made more explicit instead of quietly absorbed. When the pipeline fails, teams understand why—fast.

2025 is the year the platform became operable, trustworthy, and honest.

= What's next

In a nutshell 2026 will focus on reliability, stability, and earning trust.

Reliability baked in from day one, so new services ship with safe defaults instead of learned constraints. 

Finish pending platfrom migrations so that legacy environments can be deprecated to eliminate risks. 

Observability will provide the feedback loop. Traces, delivery metrics, and runtime signals will aim to make it clearer what improves and what does not.

The objective is simple: fewer surprises, faster recovery, and systems that earn trust by default.


= References Links

#label("ref1") 1. #link("https://technestsl.atlassian.net/wiki/spaces/PSEC/pages/746094609/AWS+Q+developer+subscriptions+ITSM+Guide")[Agentic AI via Amazon Q Developer]

#v(0mm)
#label("ref2") 2. #link("https://technestsl.atlassian.net/wiki/spaces/Innovation/pages/688423012/2025-08+Intelligent+Change+Log+and+Release+Notes+generation")[Intelligent Changelog Release Notes]

#v(0mm)
#label("ref3") 3. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/629637133/HOWTO+Request+AI+to+work+in+your+Merge+Requests")[How To Request AI work in your Merge Request]

#v(0mm)
#label("ref4") 4. #link("https://lab.technest.es/fortris/platform/pipelines/platform-cicd-pipelines/-/merge_requests/228")[AI root cause analysis in failed sync pipeline jobs]

#v(0mm)
#label("ref5") 5. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/199918392/HOW-TO+Provision+dynamic+preview+ephemeral+applications+using+merge+requests+and+Argo+CD")[How to request preview environments]

#v(0mm)
#label("ref6") 6. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/444694643/HOWTO+Deploy+MongoDB+clusters+with+cams-mongodb-helm-chart")[How to deploy MongoDB in Kubernetes]

#v(0mm)
#label("ref7") 7. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/396525830/HOWTO+Create+a+Database+on+a+existing+MongoDB+instance+in+Kubernetes")[How to create a Mongo database on Kubernetes]

#v(0mm)
#label("ref8") 8. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/355041742/SPIKE+Integrate+Infisical+in+cams-base-chart")[Integrate Infisical]


#v(0mm)
#label("re9") 9. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/450363393/HOWTO+Deploy+Redis+clusters+with+cams-redis-helm-chart")[How to Deploy Redis Clusters]

#v(0mm)
#label("re10") 10. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/258605135/2025+-+Platform+Monthly+Show+and+Tell")[Platform 2025 Monthly Show & Tell]

#v(0mm)
#label("re10") 11. #link("https://technestsl.atlassian.net/wiki/spaces/PLATFORM/pages/812548128/2026+-+Platform+Team+Objetives")[Platform 2026 Roadmap]






#v(100mm)
= The Team
Meet the team that was at the forefront of the above


#v(3mm)
#align(left)[
  #block(
    width: 80mm,
    stroke: 1.2pt + rgb("#F07C70"),
    radius: 15mm,
    inset: 3pt,
  )[
    #box(clip: true, radius: 15mm)[
      #image("platform.jpg", width: 100%, height: 55mm, fit: "cover")
    ]
  ]
]
#align(center)[Platform Team]
#v(1000mm)
